key: RcGkqmPyur+9o+VYKE1AYB2QYfFexGFuWrCSwD2BWl7TTi49AyCiMeyc7NIdTgi1N3x+mLLKZLo5wwyoyoHH6gpsNctwmbLvfgw0t+JVc4922uDUjDlK0GO6l399a981NnnYfEtrW8Y+po3Yj11QDJ1ynw8H2UJl2c/CuB+9WVc7fs5XSSXi+WRLDgcrgnGoYAlrzqUw23Zc2yDROT+DxqQKvIntNoCocfzhCBods7W7UrCv2CfiWFTIretXyi32I57B+JCsHeO+0xBX7ap77IcHzO0wBiFwgVAoy9uYJ6PpqDONOv5SGoPOd/p7JVfqNGLnA5MM9shidGeHmQVjEIHeJr15kB6JcvVDO3Q9gY7ODpjA/Ih+6rgSG4M/jRJuGscHi12FQnLGPQpN4wdm/gyq46aaNMc5ci4bIAFj/lzdLSbJ7YQ3MjUa8t7m00FT4SQfW0SvPqEO4AxT1833QcIxYW/LnrSe8hlvFmb1hOfnvK6ZXgj9+ebX8uSOSZ9CjgSSRXpoozIL9ja5rGOi9FQ63RMIkD1tQ3ZHl67amKGVfqfEdVyfowDw25kjKSKpWsFjKgpEWKGBdlz5/VKkle6i4G4sEn+NXIpqpOdIk/YuT6RPXq9Vh/3fsYTHIIT3PqTrNQjDi05iDqDj0jzQfQ==
metrics:
  plugins:
    - name: jvmjolokia
      interval: 300
      enabled: true
      config:
        ip: 172.31.255.140
        password: admin
        protocol: http
        username: admin
        port: 8778
        context: jolokia
        monitorDeadlocks: false
        deadLockMonitoringInterval: 300
